- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Create Nginx configuration directory
  ansible.builtin.file:
    path: /etc/nginx/sites-available
    state: directory
    mode: "0755"

- name: Create Nginx configuration file
  ansible.builtin.copy:
    src: reverse_proxy.conf
    dest: /etc/nginx/sites-available/reverse-proxy.conf
    mode: "0755"
  notify: Restart Nginx

- name: Create symbolic link for the configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/reverse-proxy.conf
    dest: /etc/nginx/sites-enabled/reverse-proxy.conf
    state: link
    mode: "0755"
  notify: Restart Nginx

- name: Delete default nginx configuration
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart Nginx
