- name: Update and install prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Prometheus configuration file
  ansible.builtin.template:
    src: prometheus.yaml.j2
    dest: "/etc/prometheus/prometheus.yml"
    mode: "0755"
  vars:
    webservers: "{{ groups['webservers'] }}"
    loadbalancer: "{{ groups['loadbalancer'] }}"
  notify: Restart Prometheus

- name: Start prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: true
