- name: Update and install prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes
    cache_valid_time: 3600
- name: Prometheus configuration file
  template:
    src: prometheus.yaml.j2
    dest: "/etc/prometheus/prometheus.yml"
    mode: 0755
  vars:
    webservers: "{{ groups['webservers'] }}"
    loadbalancer: "{{ groups['loadbalancer'] }}"
  notify: Restart Prometheus
- name: Start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
