---
- name: Deploy App
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Include webserver task list
      ansible.builtin.import_tasks:
        file: webserver.yaml
      when: inventory_hostname in groups["webservers"]
    - name: Include Nginx configuration
      ansible.builtin.import_tasks:
        file: nginx.yaml
      when: inventory_hostname in groups["webservers"]
    - name: Include Load Balancer configuration
      ansible.builtin.import_tasks:
        file: load-balancer.yaml
      when: inventory_hostname in groups["loadbalancer"]
    - name: Include Prometheus configuration
      ansible.builtin.import_tasks:
        file: prometheus.yaml
      when: inventory_hostname in groups["monitoring"]
    - name: Include Grafana configuration
      ansible.builtin.import_tasks:
        file: grafana.yaml
      when: inventory_hostname in groups["monitoring"]

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: restart_prometheus
      systemd:
        name: prometheus
        state: restarted
        enabled: yes
        daemon_reload: yes

  