- name: Install Nginx
  apt:
    name: nginx
    state: latest
- name: Create Nginx configuration directory
  file:
    path: /etc/nginx/sites-available
    state: directory
- name: Create Nginx configuration file
  copy:
    src: reverse_proxy.conf
    dest: /etc/nginx/sites-available/reverse-proxy.conf
  notify: Restart Nginx
- name: Create symbolic link for the configuration
  file:
    src: /etc/nginx/sites-available/reverse-proxy.conf
    dest: /etc/nginx/sites-enabled/reverse-proxy.conf
    state: link
  notify: Restart Nginx
- name: Delete default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart Nginx