- name: update and install prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes
    cache_valid_time: 3600
- name: prometheus configuration file
  template:
    src: prometheus.yaml.j2
    dest: "/etc/prometheus/prometheus.yml"
    mode: 0755
  notify: restart_prometheus
- name: start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
