name: Deployment Workflow

on:
  push:
    branches:
      - main
      - dev
      - release*
  pull_request:
    branches:
      - main
      - dev
      - release*

env:
  WORKSPACE: ${{github.ref_name}}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: self-hosted

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: danimithil/coffee-project
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  terraform-provisioning:
    name: Create resources using terraform
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup fresh SSH keys
        run: |
          ssh-keygen -t rsa -b 4096 -C "mresham" -f ~/.ssh/id_rsa -N '' <<< y

      - name: Initialize
        run: terraform init
        working-directory: ./terraform-files

      - name: Create Workspace
        run: terraform workspace select -or-create=true $WORKSPACE
        working-directory: ./terraform-files

      - name: Create plan
        run: terraform plan -input=false
        working-directory: ./terraform-files

      - name: Create resources
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform-files

      - name: Output External IP
        id: external_ip
        run: |
          terraform refresh
          echo "::set-output name=external_ip::$(terraform output -raw external_ip)"
        working-directory: ./terraform-files

    outputs:
      external_ip: ${{ steps.external_ip.outputs.external_ip }}

  ansible-configuration:
    name: Configure server using ansible
    runs-on: self-hosted
    needs: terraform-provisioning

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      # FIXME: Uncomment before merging #23
      # - name: Trigger Ansible playbook
      #   run: |
      #     external_ip=${{ needs.terraform-provisioning.outputs.external_ip }}
      #     ansible-playbook -i "${external_ip}," --private-key=~/.ssh/id_rsa deployment.yaml
      #   working-directory: ./ansible

      # Comment below step to disable resource destroy when #23 is able to successfully deploy the app
      - name: Destroy resources
        run: |
          terraform init
          terraform workspace select $WORKSPACE
          terraform destroy -auto-approve -input=false
        working-directory: ./terraform-files
