name: Node.js Scan Static Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
      - release*

jobs:
  nodejs-scan:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install node scanning tool
        uses: actions/setup-python@v4
        with:
          cache: "pip" # caching pip to avoid multiple installs

      - name: Run njsscan
        run: |
          pip install njsscan
          /home/mresham/.local/bin/njsscan .
        working-directory: ./coffee-project
