name: Node.js Scan Static Analysis

on:
  push:

jobs:
  nodejs-scan:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install node scanning tool
        uses: actions/setup-python@v4
        with:
          cache: "pip"

      - name: Run njsscan
        run: |
          pip install njsscan
          njsscan .
        working-directory: ./coffee-project
