name: Node.js Scan Static Analysis

# on:
#   push
#   branches:
#     - main
#     - dev
#     - release*
#     - 24-static-analysis
# pull_request:
#   branches:
#     - main
#     - dev
#     - release*
#     - 24-static-analysis

on:
  push

  # pull_request:
  #   branches:
  #     - main
  #     - dev
  #     - release*

jobs:
  nodejs-scan:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: njsscan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: "."
