name: Terraform Provisioning - Plan

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - dev

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.3

      - name: Initialize
        run: terraform init

      - name: Create Workspaces
        run: |
          terraform workspace new dev
          terraform workspace new release
          terraform workspace new prod

      - name: Select dev workspace and create plan
        run: |
          terraform workspace select dev
          terraform plan -out=tfplan
