name: Terraform Provisioning - Plan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
      - release*

env:
  WORKSPACE: dev
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Initialize
        run: terraform init
        working-directory: ./terraform-files

      - name: Create Workspace
        run: terraform workspace select -or-create=true $WORKSPACE
        working-directory: ./terraform-files

      - name: Create plan
        run: terraform plan -input=false
        working-directory: ./terraform-files

      - name: Create resources
        # FIXME: Uncomment below code to perform apply action only on push to the dev branch
        # if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform-files

      # FIXME: To be deleted/commented before merging to dev
      # - name: Destroy resources
      #   run: terraform destroy -auto-approve -input=false
