name: Terraform Provisioning - Plan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
      - release*

env:
  WORKSPACE: dev

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Initialize
        run: terraform init
        working-directory: ./terraform-files

      - name: Create Workspaces
        run: |
          terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE
        working-directory: ./terraform-files

      - name: Select dev workspace and create plan
        run: |
          terraform workspace select dev
          terraform plan -out=tfplan
        working-directory: ./terraform-files
