name: Terraform Provisioning Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
      - release*

env:
  WORKSPACE: dev
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  KEY_FILE: ~/ssh/id_rsa

jobs:
  terraform-provisioning:
    name: Creating resources using terraform
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Configure SSH Keys
        run: |
          mkdir -p ~/ssh
          ssh-keygen -t rsa -f $KEY_FILE -N "" -C jmulani2 <<< y

      - name: Initialize
        run: terraform init
        working-directory: ./terraform-files

      - name: Create Workspace
        run: terraform workspace select -or-create=true $WORKSPACE
        working-directory: ./terraform-files

      - name: Create plan
        run: terraform plan -input=false
        working-directory: ./terraform-files

      - name: Create resources
        # Comment below line while testing workflow
        # if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform-files

      # Uncomment below step while testing workflow
      # - name: Destroy resources
      #   run: terraform destroy -auto-approve -input=false
      #   working-directory: ./terraform-files

      - name: Trigger Ansible playbook
        # Comment below line while testing workflow
        # if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: |
          external_ip=$(terraform output -raw external_ip) 
          ansible-playbook -i ${external_ip} --private-key $KEY_FILE -u jmulani2 deployment.yaml
        working-directory: ./ansible
