name: Lint terraform code

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
#       - dev
#       - release*

on: push

jobs:
  tflint:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install tflint
        run: |
          curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_Linux_x86_64\.zip")" -o tflint.zip
          unzip tflint.zip
          sudo mv tflint /usr/local/bin/
          rm tflint.zip

      - name: Lint files
        run: |
          tflint
        working-directory: ./terraform-files
